Cleaning up entrypoint and systemd scripts: Better describe what's going on.

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -4,44 +4,50 @@ PATH="$DEVSHOP_PATH/bin:$PATH"
 
 set -e
 
-log() {
-  echo "DevShop | entrypoint | $@";
-}
-
-echo "   ____              ____  _                      "
-echo "  |  _ \  _____   __/ ___|| |__   ___  _ __       "
-echo "  | | | |/ _ \ \ / /\___ \| '_ \ / _ \| '_ \      "
-echo "  | |_| |  __/\ V /  ___) | | | | (_) | |_) |     "
-echo "  |____/ \___| \_/  |____/|_| |_|\___/| .__/      "
-echo "           http://getdevshop.com      |_|         "
-echo "__________________________________________________"
-echo ""
-echo "              Docker Entrypoint                   "
-echo "__________________________________________________"
+devshop-logo "Docker Entrypoint"
 
 # Set ANSIBLE_TAGS from environment variable ANSIBLE_TAGS, or use ANSIBLE_TAGS_RUNTIME.
 ANSIBLE_TAGS=${ANSIBLE_TAGS:-runtime}
 DOCKER_COMMAND=${@:-devshop-ansible-playbook}
 DOCKER_COMMAND_POST=${DOCKER_COMMAND_POST:-"echo 'Docker command $DOCKER_COMMAND complete!'"}
-ENTRYPOINT_COMMAND=${ENTRYPOINT_COMMAND:-docker-systemd}
+INIT_COMMAND=${INIT_COMMAND:-docker-systemd}
 
-log "Docker Command: $DOCKER_COMMAND"
-log "Secondary Docker Command: $DOCKER_SECONDARY_COMMAND"
-log "Init Command: $ENTRYPOINT_COMMAND"
-
-echo "Environment:"
-env | grep "ANSIBLE_" || echo "No Ansible Variables found."
+DEBUG_ENVIRONMENT=${DEBUG_ENVIRONMENT:-ANSIBLE_}
 
 if [ -n "${DEVSHOP_ENTRYPOINT_LOG_FILES}" ]; then
-  log "Tailing logs: $DEVSHOP_ENTRYPOINT_LOG_FILES"
-  tail-file --follow --retry --verbose $DEVSHOP_ENTRYPOINT_LOG_FILES &
+  DOCKER_COMMAND_LOGS="tail-file --follow --verbose $DEVSHOP_ENTRYPOINT_LOG_FILES"
+  echo "Tailing Log Files: $DEVSHOP_ENTRYPOINT_LOG_FILES"
+  echo 'TIP: Set the $DEVSHOP_ENTRYPOINT_LOG_FILES environment variable to change the files to show in the Docker logs.'
+  devshop-line
 else
-  log 'No files being output. Set $DEVSHOP_ENTRYPOINT_LOG_FILES variable with a list of files to tail.'
+  echo 'WARNING: $DEVSHOP_ENTRYPOINT_LOG_FILES variable was empty. Not showing any log files.'
+  devshop-line
 fi
 
-log "Launching Docker Command in a new process: $DOCKER_COMMAND"
-(sleep 3 && $DOCKER_COMMAND && $DOCKER_COMMAND_POST) &
+echo "The following commands will be run in this container: "
+echo "INIT_COMMAND:        $INIT_COMMAND"
+echo "DOCKER_COMMAND:      $DOCKER_COMMAND"
+echo "DOCKER_COMMAND_POST: $DOCKER_COMMAND_POST"
+echo "DOCKER_COMMAND_LOGS: $DOCKER_COMMAND_LOGS"
+devshop-line
+echo "Container Environment:"
+env | grep "${DEBUG_ENVIRONMENT}" || echo "No Variables with a name containing '${DEBUG_ENVIRONMENT}' found."
+echo 'TIP: Set the $DEBUG_ENVIRONMENT environment variable to a variable name (or partial string) to print out values.'
+devshop-line
+
+log "Launching Docker Commands in a new process..."
+((sleep 3 && \
+  devshop-logo "Running DOCKER_COMMAND: $DOCKER_COMMAND ..." && $DOCKER_COMMAND &&
+  devshop-logo "Running DOCKER_COMMAND_POST: $DOCKER_COMMAND_POST ..." && $DOCKER_COMMAND_POST && \
+  devshop-logo "Running DOCKER_COMMAND_LOGS: $DOCKER_COMMAND_LOGS ..." && $DOCKER_COMMAND_LOGS \
+) || (echo "Command failed!" && exit 1)) &
+
+DOCKER_COMMANDS_PID=$!
+
+echo "Docker Commands PID: $DOCKER_COMMAND_PID"
+
+devshop-line
 
 # We keep this as devshop-systemd because systemd must run as PID 1.
-log "Running Init Command: $ENTRYPOINT_COMMAND"
-exec "$ENTRYPOINT_COMMAND"
+log "Running Init Command: $INIT_COMMAND"
+exec "$INIT_COMMAND"
