Fixing bad messaging and action to take when Docker command fails.

diff --git a/docker/bin/docker-systemd-entrypoint b/docker/bin/docker-systemd-entrypoint
--- a/docker/bin/docker-systemd-entrypoint
+++ b/docker/bin/docker-systemd-entrypoint
@@ -85,7 +85,8 @@ if [ ! -z "$DOCKER_COMMAND" ]; then
               fi
             )
         ) || (
-          echo "The DEVSHOP_DOCKER_COMMAND_RUN failed. (exit $?) Continuing on. If you wish to exit on failure, run the command as the docker 'command' instead."
+          echo "The DOCKER_COMMAND failed. (exit $?) Triggering a shutdown to end INIT_COMMAND ..." && \
+          shutdown
         )
 
     ) || ( \
