Ensure the Docker command is empty by default, and improve messages around it.

diff --git a/docker/bin/docker-systemd-entrypoint b/docker/bin/docker-systemd-entrypoint
--- a/docker/bin/docker-systemd-entrypoint
+++ b/docker/bin/docker-systemd-entrypoint
@@ -9,7 +9,7 @@ set -e
 #
 # The DOCKER_COMMAND is the actual Docker CMD used for this container image.
 # $@ is every argument and option passed to the entrypoint (which is the same way CMD/ENTRPOINT work)
-DOCKER_COMMAND=${@:-watch uptime}
+DOCKER_COMMAND=${@}
 SYSTEM_STATUS_COMMAND=${SYSTEM_STATUS_COMMAND:-systemctl status --no-pager}
 
 echo "Hi! I'm docker-systemd-entrypoint."
@@ -28,13 +28,16 @@ if [ ! -z "$DOCKER_COMMAND" ]; then
     #  Sleep for 3 seconds, to allow INIT_COMMAND to launch.
     #  Run $DOCKER_COMMAND, and exit with it's exit code.
     ((sleep ${INIT_COMMAND_WAIT:-3} && \
-      echo "Checking system status ..." && $SYSTEM_STATUS_COMMAND &&
+      echo "System Status before running DOCKER_COMMAND: " && $SYSTEM_STATUS_COMMAND &&
       echo "Running Docker Command '$DOCKER_COMMAND' ..." && $DOCKER_COMMAND &&
         # If not successful, kill the container.
         # If successful, mention that system D continues.
-        echo "DOCKER_COMMAND completed (exit 0). SystemD continues.") || ( \
-        echo "DOCKER_COMMAND failed. (exit $?) ... Exiting the container." && \
-            shutdown )) &
+        echo "The DOCKER_COMMAND completed. (exit 0) Remember: INIT_COMMAND may continue to run." && \
+        echo "System Status after running DOCKER_COMMAND: " && $SYSTEM_STATUS_COMMAND \
+    ) || ( \
+        echo "The DOCKER_COMMAND failed. (exit $?) Triggering a shutdown to end INIT_COMMAND ..." && \
+            shutdown
+    )) &
   DOCKER_COMMAND_PID=$!
   echo "The Docker Command is about to start with PID $DOCKER_COMMAND_PID ..."
 
