Cherry picking docker folder changes from feature/ch475/better-install-sh#98bfaef67861b9032a55fc5243e54a4c441a4216

diff --git a/docker/bin/docker-systemd-entrypoint b/docker/bin/docker-systemd-entrypoint
--- a/docker/bin/docker-systemd-entrypoint
+++ b/docker/bin/docker-systemd-entrypoint
@@ -14,17 +14,40 @@ DOCKER_COMMAND_POST=${DOCKER_COMMAND_POST:-"echo 'No DOCKER_COMMAND_POST variabl
 SYSTEM_STATUS_COMMAND=${SYSTEM_STATUS_COMMAND:-systemctl status --no-pager}
 WELCOME_MESSAGE="Enjoy the DevShop Containers!"
 
+DEVSHOP_PATH="$( cd "$(dirname "$0")"/.. ; pwd -P )"
 PATH="$DEVSHOP_PATH/bin:$DEVSHOP_PATH/scripts:$PATH"
 export PATH
 
-devshop-logo "Docker Entrypoint"
+devshop_logo() {
+  echo '
+    ____              ____  _
+   |  _ \  _____   __/ ___|| |__   ___  _ __
+   | | | |/ _ \ \ / /\___ \|  _ \ / _ \|  _ \
+   | |_| |  __/\ V /  ___) | | | | (_) | |_) |
+   |____/ \___| \_/  |____/|_| |_|\___/| .__/
+            http://getdevshop.com      |_|'
+  if [ -z "$1" ]; then exit; fi
+
+  devshop_line
+  echo " $1 "
+  devshop_line
+}
+
+devshop_line() {
+  CHARACTER="${1:--}"
+  COLUMNS="$2"
+  printf '%*s\n' "${COLUMNS:-$(tput cols -T xterm)}" '' | tr ' ' $CHARACTER
+}
+
+devshop_logo "Starting /docker/bin/docker-systemd-entrypoint..."
 
 echo "Hi! I'm docker-systemd-entrypoint."
 echo "In a few seconds, I'm going to launch the Docker Command you specified as a new process."
 echo "Then, I'm going to pass my process off to SystemD!"
 echo "That way, you can specify any docker CMD but it will run inside a container with SystemD running properly."
 
-devshop-log "Environment Variables"
+devshop_line
+echo "Environment Variables"
 
 echo "INIT_COMMAND: $INIT_COMMAND"
 echo "DOCKER_COMMAND: $DOCKER_COMMAND"
@@ -33,15 +56,8 @@ echo "DOCKER_COMMAND_POST: $DOCKER_COMMAND_POST"
 echo "SYSTEM_STATUS_COMMAND: $SYSTEM_STATUS_COMMAND"
 echo "PATH: $PATH"
 
-devshop-log "The following commands will be run in this container: "
-
-echo "INIT_COMMAND:        $INIT_COMMAND"
-echo "DOCKER_COMMAND:      $DOCKER_COMMAND"
-echo "DEVSHOP_DOCKER_COMMAND_RUN: $DEVSHOP_DOCKER_COMMAND_RUN"
-echo "DOCKER_COMMAND_POST: $DOCKER_COMMAND_POST"
-echo "DOCKER_COMMAND_LOGS: $DOCKER_COMMAND_LOGS"
-
-devshop-log "Starting command chain..."
+devshop_line
+echo "Starting command chain..."
 
 if [ ! -z "$DOCKER_COMMAND" ]; then
     # This launches a group of commands in a new process:
@@ -69,7 +85,8 @@ if [ ! -z "$DOCKER_COMMAND" ]; then
               fi
             )
         ) || (
-          echo "The DEVSHOP_DOCKER_COMMAND_RUN failed. (exit $?) Continuing on. If you wish to exit on failure, run the command as the docker 'command' instead."
+          echo "The DOCKER_COMMAND failed. (exit $?) Triggering a shutdown to end INIT_COMMAND ..." && \
+          shutdown
         )
 
     ) || ( \
